package osbot.account;

public enum AccountStage {
//	'TUT_ISLAND','QUEST_COOK_ASSISTANT','QUEST_ROMEO_AND_JULIET'

	MULE_TRADING,
	UNKNOWN,
	GE_SELL_BUY_MINING,
	WOODCUTTING_GOLD_FARM,
	MINING_IRON_ORE,
	RIMMINGTON_IRON_ORE,
	MINING_LEVEL_TO_15,
	QUEST_ROMEO_AND_JULIET,
	QUEST_SHEEP_SHEARER,
	QUEST_DORICS_QUEST,
	QUEST_COOK_ASSISTANT,
	MINING_RIMMINGTON_CLAY,
	OBSTACLE_TEST,
	TUT_ISLAND,
}
