package osbot.account;

public enum AccountStage {
//	'TUT_ISLAND','QUEST_COOK_ASSISTANT','QUEST_ROMEO_AND_JULIET'
	
	TUT_ISLAND,
	QUEST_COOK_ASSISTANT,
	QUEST_ROMEO_AND_JULIET,
	QUEST_SHEEP_SHEARER,
	UNKNOWN
}
